const CHANGE_AUTH_STATUS = `@auth/CHANGE_AUTH_STATUS`;
const STORE_USER_DATA = `@auth/STORE_USER_DATA`;
const REDIRECT_TO_ROUTE = `@auth/REDIRECT_TO_ROUTE`;

export {
  CHANGE_AUTH_STATUS,
  STORE_USER_DATA,
  REDIRECT_TO_ROUTE,
};
