const STORE_OFFERS = `@offers/STORE_OFFERS`;
const STORE_HOTEL_DATA = `@offers/STORE_HOTEL_DATA`;
const UPDATE_OFFER = `@offers/UPDATE_OFFER`;
const CHANGE_SORT = `@offers/CHANGE_SORT`;
const STORE_FAVORITE_DATA = `@offers/STORE_FAVORITE_DATA`;
const STORE_NEARBY_OFFERS = `@offers/STORE_NEARBY_OFFERS`;

export {
  STORE_OFFERS,
  STORE_HOTEL_DATA,
  UPDATE_OFFER,
  CHANGE_SORT,
  STORE_FAVORITE_DATA,
  STORE_NEARBY_OFFERS,
};
